# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-08 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openprofession', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='student_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
