# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-16 10:36
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('openprofession', '0002_auto_20171208_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('second_name', models.CharField(max_length=255, verbose_name='Отчество')),
                ('sex', models.CharField(choices=[('m', 'мужской'), ('f', 'женский')], max_length=1, verbose_name='Пол')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('address_register', models.TextField(verbose_name='Адрес регистрации')),
                ('address_living', models.TextField(verbose_name='Адрес проживания')),
                ('claim_scan', models.FileField(upload_to='', verbose_name='Скан заявления')),
                ('series', models.CharField(max_length=8, verbose_name='Серия')),
                ('number', models.CharField(max_length=8, verbose_name='Номер')),
                ('issued_by', models.TextField(verbose_name='Кем выдан')),
                ('unit_code', models.CharField(max_length=16, verbose_name='Код подразделения')),
                ('issue_date', models.DateField(verbose_name='Дата выдачи')),
                ('passport_scan', models.FileField(upload_to='', verbose_name='Скан заявления')),
                ('education_level', models.CharField(choices=[('M', 'Среднее профессиональное'), ('H', 'Высшее')], max_length=1, verbose_name='Уровень базового образования')),
            ],
        ),
    ]
