# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-16 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openprofession', '0003_personaldata'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldata',
            name='agreement',
            field=models.BooleanField(default=False, verbose_name='Согласие на обработку перс. данных'),
        ),
    ]
