# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-16 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openprofession', '0004_personaldata_agreement'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldata',
            name='diploma_scan',
            field=models.FileField(null=True, upload_to='uploads/', verbose_name='Скан диплома'),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='claim_scan',
            field=models.FileField(upload_to='uploads/', verbose_name='Скан заявления'),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='passport_scan',
            field=models.FileField(upload_to='uploads/', verbose_name='Скан заявления'),
        ),
    ]
