# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-16 12:48
from __future__ import unicode_literals

from django.db import migrations, models
import openprofession.models


class Migration(migrations.Migration):

    dependencies = [
        ('openprofession', '0005_auto_20171216_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldata',
            name='claim_scan',
            field=models.FileField(upload_to=openprofession.models.generate_new_filename, verbose_name='Скан заявления'),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='diploma_scan',
            field=models.FileField(null=True, upload_to=openprofession.models.generate_new_filename, verbose_name='Скан диплома'),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='passport_scan',
            field=models.FileField(upload_to=openprofession.models.generate_new_filename, verbose_name='Скан заявления'),
        ),
    ]
