# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-18 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openprofession', '0006_auto_20171216_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldata',
            name='birth_date',
            field=models.CharField(max_length=16, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='issue_date',
            field=models.CharField(max_length=16, verbose_name='Дата выдачи'),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='phone',
            field=models.CharField(max_length=255, verbose_name='Телефон'),
        ),
    ]
