# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-19 08:05
from __future__ import unicode_literals

from django.db import migrations, models
import openprofession.models


class Migration(migrations.Migration):

    dependencies = [
        ('openprofession', '0008_auto_20180119_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldata',
            name='another_doc',
            field=models.FileField(null=True, upload_to=openprofession.models.generate_new_filename, verbose_name='Иной документ'),
        ),
    ]
