# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-19 12:12
from __future__ import unicode_literals

from django.db import migrations, models
import openprofession.models


class Migration(migrations.Migration):

    dependencies = [
        ('openprofession', '0010_quotesavailable'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldata',
            name='doc_forwarding',
            field=models.FileField(null=True, upload_to=openprofession.models.generate_new_filename, verbose_name='Скан заявления о пересылке'),
        ),
        migrations.AddField(
            model_name='personaldata',
            name='job',
            field=models.CharField(max_length=2048, null=True, verbose_name='Место работы'),
        ),
        migrations.AddField(
            model_name='personaldata',
            name='position',
            field=models.CharField(max_length=2048, null=True, verbose_name='Должность'),
        ),
    ]
