# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-20 12:15
from __future__ import unicode_literals

from django.db import migrations, models
import openprofession.models


class Migration(migrations.Migration):

    dependencies = [
        ('openprofession', '0011_auto_20180119_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024, verbose_name='Имя файла отчета')),
                ('report_file', models.FileField(null=True, upload_to=openprofession.models.generate_new_report_filename, verbose_name='Файл отчета')),
                ('report_type', models.CharField(max_length=32, verbose_name='Тип отчета')),
                ('date', models.DateTimeField(verbose_name='Дата генерации отчета')),
                ('course_id', models.CharField(max_length=32, verbose_name='ИД курса')),
                ('session', models.CharField(max_length=32, verbose_name='Сессия')),
            ],
        ),
        migrations.CreateModel(
            name='ReportEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255, verbose_name='Идентификатор студента')),
                ('email', models.CharField(max_length=255, verbose_name='Электронная почта')),
                ('username', models.CharField(max_length=255, verbose_name='Имя пользователя')),
                ('grade', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Оценка за весь курс')),
                ('cohort_name', models.CharField(max_length=255, verbose_name='Название когорты')),
                ('enrollment_track', models.CharField(max_length=255, verbose_name='Тип подписка')),
                ('certificate_eligible', models.BooleanField(default=False, verbose_name='Проходит ли на сертификат')),
                ('certificate_delivered', models.CharField(max_length=255, verbose_name='Сертификат доставлен')),
                ('certificate', models.CharField(max_length=255, verbose_name='Сертификат')),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='entries',
            field=models.ManyToManyField(to='openprofession.ReportEntry'),
        ),
    ]
