# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-20 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openprofession', '0013_reportentry_raw_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='course_id',
            field=models.CharField(default='-', max_length=1024, verbose_name='Ид курса'),
        ),
    ]
