# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-20 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openprofession', '0014_program_course_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='processed',
            field=models.BooleanField(default=False, verbose_name='Обработано'),
        ),
    ]
