# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-20 14:03
from __future__ import unicode_literals

from django.db import migrations, models
import openprofession.models


class Migration(migrations.Migration):

    dependencies = [
        ('openprofession', '0015_report_processed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldata',
            name='address_living',
            field=models.TextField(blank=True, null=True, verbose_name='Адрес проживания'),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='address_register',
            field=models.TextField(blank=True, null=True, verbose_name='Адрес регистрации'),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='issue_date',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Дата выдачи'),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='issued_by',
            field=models.TextField(blank=True, null=True, verbose_name='Кем выдан'),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='number',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='passport_scan',
            field=models.FileField(blank=True, null=True, upload_to=openprofession.models.generate_new_filename, verbose_name='Скан заявления'),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='series',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Серия'),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='unit_code',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Код подразделения'),
        ),
    ]
