# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-22 12:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openprofession', '0016_auto_20180120_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldata',
            name='city',
            field=models.CharField(max_length=256, null=True, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='openprofession.Program'),
        ),
    ]
