# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-23 05:57
from __future__ import unicode_literals

from django.db import migrations, models
import openprofession.models


class Migration(migrations.Migration):

    dependencies = [
        ('openprofession', '0017_auto_20180122_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldata',
            name='another_doc',
            field=models.FileField(blank=True, null=True, upload_to=openprofession.models.generate_new_filename, verbose_name='Иной документ'),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='diploma_scan',
            field=models.FileField(blank=True, null=True, upload_to=openprofession.models.generate_new_filename, verbose_name='Скан диплома'),
        ),
        migrations.AlterField(
            model_name='reportentry',
            name='certificate',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Сертификат'),
        ),
    ]
