# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-24 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openprofession', '0019_auto_20180123_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldata',
            name='courses',
            field=models.ManyToManyField(blank=True, null=True, related_name='personaldata_requests_created', to='openprofession.Program'),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='entries',
            field=models.ManyToManyField(blank=True, null=True, related_name='personaldata_requests_created', to='openprofession.ReportEntry'),
        ),
    ]
