# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-24 08:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openprofession', '0021_auto_20180124_1304'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personaldata',
            options={'verbose_name': 'слушатель', 'verbose_name_plural': 'слушатели'},
        ),
        migrations.AlterModelOptions(
            name='program',
            options={'verbose_name': 'курс', 'verbose_name_plural': 'курсы'},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'verbose_name': 'отчет', 'verbose_name_plural': 'отчеты'},
        ),
        migrations.AddField(
            model_name='report',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='openprofession.Program'),
        ),
    ]
