# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-24 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openprofession', '0022_auto_20180124_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldata',
            name='program_grade',
            field=models.CharField(default='-1', max_length=32, verbose_name='Оценка за выбранный курс'),
        ),
    ]
