# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-24 13:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openprofession', '0025_auto_20180124_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseUserGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Оценка за весь курс')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openprofession.Program')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openprofession.PersonalData')),
            ],
        ),
    ]
