# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-24 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openprofession', '0026_courseusergrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='start',
            field=models.IntegerField(default=1, verbose_name='Старт'),
        ),
    ]
