# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-25 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openprofession', '0027_program_start'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={'verbose_name': 'программа', 'verbose_name_plural': 'программы'},
        ),
        migrations.AlterField(
            model_name='program',
            name='start',
            field=models.IntegerField(default=-1, verbose_name='Старт'),
        ),
    ]
