# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-25 09:25
from __future__ import unicode_literals

from django.db import migrations, models
import openprofession.models


class Migration(migrations.Migration):

    dependencies = [
        ('openprofession', '0028_auto_20180125_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldata',
            name='doc_forwarding',
            field=models.FileField(blank=True, null=True, upload_to=openprofession.models.generate_new_filename, verbose_name='Скан заявления о пересылке'),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='second_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Отчество'),
        ),
    ]
