# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-25 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openprofession', '0030_auto_20180125_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldata',
            name='program_grade',
            field=models.CharField(blank=True, default='-1', max_length=32, null=True, verbose_name='Оценка за выбранный курс'),
        ),
    ]
