# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-26 07:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openprofession', '0032_auto_20180126_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaldata',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='personaldata',
            name='updated_at',
        ),
    ]
