# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-02 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openprofession', '0035_courseusergrade_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDAvailable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.BooleanField(default=False, verbose_name='Страница подачи заявки доступна')),
            ],
        ),
    ]
