# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-13 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openprofession', '0037_simulizatordata'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulizatordata',
            name='agreement',
            field=models.BooleanField(default=False, verbose_name='Согласие на обработку перс. данных'),
        ),
    ]
