# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-13 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openprofession', '0038_simulizatordata_agreement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulizatordata',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='username'),
        ),
    ]
