# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-06 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openprofession', '0039_auto_20180313_1952'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProctoredReportEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255, verbose_name='Электронная почта')),
                ('exam_name', models.CharField(blank=True, max_length=255, verbose_name='Название экзамена')),
                ('allowed_time_limit_mins', models.IntegerField(default=-1, verbose_name='Длительность экзамена')),
                ('is_sample_attempt', models.BooleanField(default=False, verbose_name='Пробная попытка')),
                ('started_at', models.CharField(blank=True, max_length=255, null=True, verbose_name='Начало экзамена')),
                ('completed_at', models.CharField(blank=True, max_length=255, null=True, verbose_name='Окончание экзамена')),
                ('status', models.CharField(max_length=255, verbose_name='Статус сдачи')),
                ('raw_data', models.TextField(default='', verbose_name='Raw')),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='proctored_entries',
            field=models.ManyToManyField(to='openprofession.ProctoredReportEntry'),
        ),
    ]
