# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-07 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openprofession', '0040_auto_20180406_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldata',
            name='possible_id',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
