# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-09 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openprofession', '0042_personaldata_proctoring_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldata',
            name='proctoring_status',
            field=models.CharField(blank=True, default='None', max_length=32, null=True, verbose_name='Статус прокторинга за выбранный курс'),
        ),
    ]
