# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-09 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openprofession', '0043_auto_20180409_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldata',
            name='exam_grade',
            field=models.CharField(blank=True, default='-1', max_length=32, null=True, verbose_name='Оценка за экзамен по программе'),
        ),
    ]
