# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-31 07:49
from __future__ import unicode_literals

from django.db import migrations, models
import openprofession.models


class Migration(migrations.Migration):

    dependencies = [
        ('openprofession', '0045_personaldata_exam_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeminarData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('second_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Отчество')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=255, verbose_name='Телефон')),
                ('job', models.CharField(max_length=2048, null=True, verbose_name='Место работы')),
                ('position', models.CharField(max_length=2048, null=True, verbose_name='Должность')),
                ('diploma_scan', models.FileField(upload_to=openprofession.models.generate_new_filename, verbose_name='Cкан документа о базовом образовании')),
                ('another_doc', models.FileField(blank=True, null=True, upload_to=openprofession.models.generate_new_filename, verbose_name='Иной документ (о смене фамилии)')),
                ('education_bid', models.FileField(blank=True, null=True, upload_to=openprofession.models.generate_new_filename, verbose_name='Скан заявления о пересылке')),
                ('doc_forwarding', models.FileField(blank=True, null=True, upload_to=openprofession.models.generate_new_filename, verbose_name='Скан заявления о пересылке')),
            ],
        ),
    ]
