# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-31 08:55
from __future__ import unicode_literals

from django.db import migrations, models
import openprofession.models


class Migration(migrations.Migration):

    dependencies = [
        ('openprofession', '0046_seminardata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminardata',
            name='another_doc',
            field=models.FileField(blank=True, null=True, upload_to=openprofession.models.generate_new_seminar_filename, verbose_name='Иной документ (о смене фамилии)'),
        ),
        migrations.AlterField(
            model_name='seminardata',
            name='diploma_scan',
            field=models.FileField(upload_to=openprofession.models.generate_new_seminar_filename, verbose_name='Cкан документа о базовом образовании'),
        ),
        migrations.AlterField(
            model_name='seminardata',
            name='doc_forwarding',
            field=models.FileField(blank=True, null=True, upload_to=openprofession.models.generate_new_seminar_filename, verbose_name='Скан заявления о пересылке'),
        ),
        migrations.AlterField(
            model_name='seminardata',
            name='education_bid',
            field=models.FileField(blank=True, null=True, upload_to=openprofession.models.generate_new_seminar_filename, verbose_name='Скан заявления о пересылке'),
        ),
    ]
