# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-31 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openprofession', '0047_auto_20180531_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminardata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='seminardata',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
