# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-05 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openprofession', '0051_auto_20180601_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminardata',
            name='with_udostoverenie',
            field=models.BooleanField(default=False, verbose_name='С получением удостоверения о повышении квалификации'),
        ),
    ]
