# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-08 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openprofession', '0052_seminardata_with_udostoverenie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminardata',
            name='type_of_participation',
            field=models.CharField(choices=[('away', 'заочно'), ('internally', 'очно'), ('internally_cert', 'очно с сертификатом')], max_length=15, verbose_name='Тип участия'),
        ),
    ]
