# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-21 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openprofession', '0053_auto_20180608_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminardata',
            name='type_of_participation',
            field=models.CharField(choices=[('away', 'заочно'), ('internally', 'очно без сертификата'), ('internally_cert', 'очно с сертификатом')], max_length=15, verbose_name='Тип участия'),
        ),
    ]
