# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-21 14:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Наименование')),
                ('short_description', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Краткое описание')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('roo_id', models.IntegerField(blank=True, null=True, verbose_name='ИД на РОО')),
                ('competences', models.TextField(blank=True, null=True, verbose_name='Формируемые компетенции')),
                ('results', models.TextField(blank=True, null=True, verbose_name='Результаты обучения')),
                ('grade_tools', models.TextField(blank=True, null=True, verbose_name='Оценочные средства')),
                ('photo', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Фото автора')),
                ('authors', models.TextField(blank=True, null=True, verbose_name='Авторы')),
                ('prerequisites', models.TextField(blank=True, null=True, verbose_name='Входные требования обучающихся')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Содержание')),
                ('directions', models.TextField(blank=True, null=True, verbose_name='Направления подготовки')),
                ('subject', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Предмет курса')),
                ('activity', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Область деятельности')),
                ('language', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Язык контента')),
                ('enrollment_end_date', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Дата окончания записи')),
                ('start_date', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Дата запуска')),
                ('duration', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Длительность курса')),
                ('labor', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Трудоемкость')),
                ('certificate', models.BooleanField(default=False, verbose_name='Трудоемкость')),
                ('proctoring_service', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Используемый сервис прокторинга')),
                ('version', models.IntegerField(blank=True, null=True, verbose_name='Номер версии курса')),
                ('opened', models.BooleanField(default=False, verbose_name='Открытый')),
                ('admin_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='e-mail администратора платформы, правообладателя')),
                ('expertized', models.BooleanField(default=False, verbose_name='Прошел обязательную экспертизу')),
                ('domain', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Предметная область')),
                ('uploaded_roo', models.BooleanField(default=False, verbose_name='Загружен курс на РОО')),
                ('uploaded_prepod', models.BooleanField(default=False, verbose_name='Загружен ли курс на prepod')),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL курса на платформе')),
                ('roo_url', models.URLField(blank=True, null=True, verbose_name='URL курса на РОО')),
                ('permission', models.BooleanField(default=False, verbose_name='Разрешение правообладателя на выгрузку')),
                ('comment', models.TextField(verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'онлайн-курс',
                'verbose_name_plural': 'онлайн-курсы',
            },
        ),
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Логин эксперта')),
            ],
            options={
                'verbose_name': 'эксперт',
                'verbose_name_plural': 'эксперт',
            },
        ),
        migrations.CreateModel(
            name='Expertise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(blank=True, max_length=1024, null=True, verbose_name='состояние процесса (этап)')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата')),
                ('type', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Вид экспертизы')),
                ('executed', models.BooleanField(default=False, verbose_name='Отметка об исполнении эксперизы')),
                ('supervisor', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Кто от ИТОО контролирует')),
                ('organizer', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Организатор экспертизы сотрудники или партнеры')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roo.Course', verbose_name='Курс')),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roo.Expert', verbose_name='Эксперт')),
            ],
            options={
                'verbose_name': 'экспертиза',
                'verbose_name_plural': 'экспертизы',
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'правообладатель',
                'verbose_name_plural': 'правообладатели',
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Наименование')),
                ('person', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Данные контактного лица правообладателя телефон, почта')),
                ('connection_form', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Форма связи с контактным лицом')),
                ('connection_date', models.DateField(blank=True, null=True, verbose_name='Дата связи с контактным лицом')),
                ('contacts', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Контакты института')),
            ],
            options={
                'verbose_name': 'платформа',
                'verbose_name_plural': 'платформы',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='roo.Owner', verbose_name='Правообладатель'),
        ),
        migrations.AddField(
            model_name='course',
            name='platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='roo.Platform', verbose_name='Название платформы'),
        ),
    ]
