# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-21 14:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roo.Owner', verbose_name='Правообладатель'),
        ),
        migrations.AlterField(
            model_name='course',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roo.Platform', verbose_name='Название платформы'),
        ),
    ]
