# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Назвнаие')),
                ('content', models.TextField(verbose_name='Контент')),
                ('weight', models.IntegerField(default=1, verbose_name='Вес')),
            ],
            options={
                'verbose_name': 'блок контента',
                'verbose_name_plural': 'блоки контента',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Назвнаие')),
                ('link', models.CharField(max_length=32, verbose_name='Ссылка')),
                ('contents', models.ManyToManyField(to='home.ContentItem')),
            ],
            options={
                'verbose_name': 'страница',
                'verbose_name_plural': 'страницы',
            },
        ),
    ]
