# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 23:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentitem',
            options={'ordering': ['-weight'], 'verbose_name': 'блок контента', 'verbose_name_plural': 'блоки контента'},
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='title',
            field=models.CharField(max_length=256, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='page',
            name='contents',
            field=models.ManyToManyField(blank=True, to='home.ContentItem'),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(max_length=256, verbose_name='Название'),
        ),
    ]
