# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-18 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20170905_0430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='link',
            field=models.CharField(max_length=256, verbose_name='Ссылка'),
        ),
    ]
