# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-05 10:22
from __future__ import unicode_literals

from django.db import migrations, models
import other.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=other.models.generate_new_filename, verbose_name='Скан заявления')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PPS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1024, null=True, verbose_name='ФИО')),
                ('conditions', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Условия привлечения')),
                ('position', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Должность, ученая степень, ученое звание')),
                ('disciplines', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Перечень читаемых дисциплин')),
                ('education', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Уровень образования, наименование специальности, направления подготовки, наименование присвоенной квалификации ')),
                ('ppk', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Сведения о дополнительном профессиональном образовании')),
                ('weight', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Регалии')),
                ('experience', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Регалии')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'преподаватель',
                'verbose_name_plural': 'преподаватели',
            },
        ),
    ]
