# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-05 12:38
from __future__ import unicode_literals

from django.db import migrations, models
import other.models


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to=other.models.generate_new_filename, verbose_name='Таблица преподавателей'),
        ),
    ]
