# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-05 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0002_auto_20180405_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='done',
            field=models.BooleanField(default=False, verbose_name='Обработано'),
        ),
        migrations.AlterField(
            model_name='pps',
            name='experience',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Стаж практической работы по профилю образовательной программы в профильных организациях с указанием периода работы и должности'),
        ),
        migrations.AlterField(
            model_name='pps',
            name='weight',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Объем учебной нагрузки по дисциплине, практикам, государственной итоговой аттестации (доля ставки)'),
        ),
    ]
