# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-05 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0003_auto_20180405_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pps',
            name='conditions',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Условия привлечения'),
        ),
        migrations.AlterField(
            model_name='pps',
            name='disciplines',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Перечень читаемых дисциплин'),
        ),
        migrations.AlterField(
            model_name='pps',
            name='education',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Уровень образования, наименование специальности, направления подготовки, наименование присвоенной квалификации '),
        ),
        migrations.AlterField(
            model_name='pps',
            name='experience',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Стаж практической работы по профилю образовательной программы в профильных организациях с указанием периода работы и должности'),
        ),
        migrations.AlterField(
            model_name='pps',
            name='name',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='pps',
            name='position',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Должность, ученая степень, ученое звание'),
        ),
        migrations.AlterField(
            model_name='pps',
            name='ppk',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Сведения о дополнительном профессиональном образовании'),
        ),
        migrations.AlterField(
            model_name='pps',
            name='weight',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Объем учебной нагрузки по дисциплине, практикам, государственной итоговой аттестации (доля ставки)'),
        ),
    ]
