# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-05 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EIOS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1', models.CharField(choices=[('y', 'Да'), ('n', 'Нет')], default='n', max_length=1, verbose_name='Есть ли у вас опыт работы в сфере онлайн-обучения')),
                ('q2', models.CharField(default='n', max_length=1, verbose_name='Какими корпоративными сервисами Уральского федерального университета вы пользуетесь?')),
                ('q3', models.CharField(choices=[(0, 'Абсолютно не согласен'), (1, 'Частично не согласен'), (2, 'Затрудняюсь ответить'), (3, 'Частично согласен'), (4, 'Абсолютно согласен')], default='0', max_length=1, verbose_name='Мне понятен термин “электронная информационно-образовательная среда”')),
                ('q4', models.CharField(choices=[(0, 'Абсолютно не согласен'), (1, 'Частично не согласен'), (2, 'Затрудняюсь ответить'), (3, 'Частично согласен'), (4, 'Абсолютно согласен')], default='0', max_length=1, verbose_name='Я понимаю, зачем нужно внедрять онлайн-обучение в образовательную деятельность')),
                ('q5', models.CharField(choices=[(0, 'Абсолютно не согласен'), (1, 'Частично не согласен'), (2, 'Затрудняюсь ответить'), (3, 'Частично согласен'), (4, 'Абсолютно согласен')], default='0', max_length=1, verbose_name='Я знаю, с помощью каких инструментов осуществляется онлайн-обучение')),
                ('q6', models.CharField(choices=[(0, 'Абсолютно не согласен'), (1, 'Частично не согласен'), (2, 'Затрудняюсь ответить'), (3, 'Частично согласен'), (4, 'Абсолютно согласен')], default='0', max_length=1, verbose_name='Меня интересует онлайн-обучение')),
                ('q7', models.CharField(choices=[(0, 'Абсолютно не согласен'), (1, 'Частично не согласен'), (2, 'Затрудняюсь ответить'), (3, 'Частично согласен'), (4, 'Абсолютно согласен')], default='0', max_length=1, verbose_name='Я понимаю финансовые аспекты использования открытых онлайн-курсов')),
                ('q8', models.CharField(choices=[(0, 'Абсолютно не согласен'), (1, 'Частично не согласен'), (2, 'Затрудняюсь ответить'), (3, 'Частично согласен'), (4, 'Абсолютно согласен')], default='0', max_length=1, verbose_name='Я понимаю, кто такой тьютор в онлайн-обучении')),
                ('q9', models.CharField(choices=[(0, 'Абсолютно не согласен'), (1, 'Частично не согласен'), (2, 'Затрудняюсь ответить'), (3, 'Частично согласен'), (4, 'Абсолютно согласен')], default='0', max_length=1, verbose_name='Мне понятны особенности планирования и реализации учебного процесса для разных моделей включения онлайн-курсов в образовательные программы')),
                ('q10', models.TextField(verbose_name='Интернет-ресурсы(сайты) наиболее полезные в вашей профессиональной деятельности')),
                ('q11', models.CharField(choices=[('m', 'Мужской'), ('f', 'Женский')], max_length=1, verbose_name='Укажите Ваш пол:')),
                ('q12', models.PositiveSmallIntegerField(choices=[('m', 'Мужской'), ('f', 'Женский')], max_length=1, verbose_name='Ваш возраст:')),
                ('q13', models.CharField(choices=[(0, '1-5'), (1, '6-10'), (2, '11-15'), (3, '16-20'), (4, 'Больше 21')], max_length=10, verbose_name='Каков Ваш опыт работы в качестве преподавателя?')),
                ('q14', models.CharField(max_length=1024, verbose_name='Наличие ученой степени:')),
                ('q15', models.EmailField(max_length=254, verbose_name='Контактная почта:')),
                ('q16', models.CharField(choices=[('y', 'Да'), ('n', 'Нет')], default='n', max_length=1, verbose_name='Интересно ли Вам дальнейшее информирование про мероприятия, связанные с онлайн-обучением)')),
            ],
        ),
    ]
