# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-05 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eios',
            name='q12',
            field=models.PositiveSmallIntegerField(choices=[('m', 'Мужской'), ('f', 'Женский')], verbose_name='Ваш возраст:'),
        ),
    ]
