# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-05 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0003_auto_20180505_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eios',
            name='q1',
            field=models.CharField(blank=True, choices=[('y', 'Да'), ('n', 'Нет')], default='n', max_length=1, null=True, verbose_name='Есть ли у вас опыт работы в сфере онлайн-обучения'),
        ),
        migrations.AlterField(
            model_name='eios',
            name='q10',
            field=models.TextField(blank=True, null=True, verbose_name='Интернет-ресурсы(сайты) наиболее полезные в вашей профессиональной деятельности'),
        ),
        migrations.AlterField(
            model_name='eios',
            name='q11',
            field=models.CharField(blank=True, choices=[('m', 'Мужской'), ('f', 'Женский')], max_length=1, null=True, verbose_name='Укажите Ваш пол:'),
        ),
        migrations.AlterField(
            model_name='eios',
            name='q12',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Ваш возраст:'),
        ),
        migrations.AlterField(
            model_name='eios',
            name='q13',
            field=models.CharField(blank=True, choices=[('0', '1-5'), ('1', '6-10'), ('2', '11-15'), ('3', '16-20'), ('4', 'Больше 21')], max_length=10, null=True, verbose_name='Каков Ваш опыт работы в качестве преподавателя?'),
        ),
        migrations.AlterField(
            model_name='eios',
            name='q14',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Наличие ученой степени:'),
        ),
        migrations.AlterField(
            model_name='eios',
            name='q15',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Контактная почта:'),
        ),
        migrations.AlterField(
            model_name='eios',
            name='q16',
            field=models.CharField(blank=True, choices=[('y', 'Да'), ('n', 'Нет')], default='n', max_length=1, null=True, verbose_name='Интересно ли Вам дальнейшее информирование про мероприятия, связанные с онлайн-обучением)'),
        ),
        migrations.AlterField(
            model_name='eios',
            name='q2',
            field=models.CharField(blank=True, default='n', max_length=1, null=True, verbose_name='Какими корпоративными сервисами Уральского федерального университета вы пользуетесь?'),
        ),
        migrations.AlterField(
            model_name='eios',
            name='q3',
            field=models.CharField(choices=[('0', 'Абсолютно не согласен'), ('1', 'Частично не согласен'), ('2', 'Затрудняюсь ответить'), ('3', 'Частично согласен'), ('4', 'Абсолютно согласен')], default='0', max_length=1, verbose_name='Мне понятен термин “электронная информационно-образовательная среда”'),
        ),
        migrations.AlterField(
            model_name='eios',
            name='q4',
            field=models.CharField(blank=True, choices=[('0', 'Абсолютно не согласен'), ('1', 'Частично не согласен'), ('2', 'Затрудняюсь ответить'), ('3', 'Частично согласен'), ('4', 'Абсолютно согласен')], default='0', max_length=1, null=True, verbose_name='Я понимаю, зачем нужно внедрять онлайн-обучение в образовательную деятельность'),
        ),
        migrations.AlterField(
            model_name='eios',
            name='q5',
            field=models.CharField(blank=True, choices=[('0', 'Абсолютно не согласен'), ('1', 'Частично не согласен'), ('2', 'Затрудняюсь ответить'), ('3', 'Частично согласен'), ('4', 'Абсолютно согласен')], default='0', max_length=1, null=True, verbose_name='Я знаю, с помощью каких инструментов осуществляется онлайн-обучение'),
        ),
        migrations.AlterField(
            model_name='eios',
            name='q6',
            field=models.CharField(blank=True, choices=[('0', 'Абсолютно не согласен'), ('1', 'Частично не согласен'), ('2', 'Затрудняюсь ответить'), ('3', 'Частично согласен'), ('4', 'Абсолютно согласен')], default='0', max_length=1, null=True, verbose_name='Меня интересует онлайн-обучение'),
        ),
        migrations.AlterField(
            model_name='eios',
            name='q7',
            field=models.CharField(blank=True, choices=[('0', 'Абсолютно не согласен'), ('1', 'Частично не согласен'), ('2', 'Затрудняюсь ответить'), ('3', 'Частично согласен'), ('4', 'Абсолютно согласен')], default='0', max_length=1, null=True, verbose_name='Я понимаю финансовые аспекты использования открытых онлайн-курсов'),
        ),
        migrations.AlterField(
            model_name='eios',
            name='q8',
            field=models.CharField(blank=True, choices=[('0', 'Абсолютно не согласен'), ('1', 'Частично не согласен'), ('2', 'Затрудняюсь ответить'), ('3', 'Частично согласен'), ('4', 'Абсолютно согласен')], default='0', max_length=1, null=True, verbose_name='Я понимаю, кто такой тьютор в онлайн-обучении'),
        ),
        migrations.AlterField(
            model_name='eios',
            name='q9',
            field=models.CharField(blank=True, choices=[('0', 'Абсолютно не согласен'), ('1', 'Частично не согласен'), ('2', 'Затрудняюсь ответить'), ('3', 'Частично согласен'), ('4', 'Абсолютно согласен')], default='0', max_length=1, null=True, verbose_name='Мне понятны особенности планирования и реализации учебного процесса для разных моделей включения онлайн-курсов в образовательные программы'),
        ),
    ]
