# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-07 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0004_auto_20180505_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eios',
            name='q1',
            field=models.CharField(choices=[('y', 'Да'), ('n', 'Нет')], default='n', max_length=1, verbose_name='Есть ли у вас опыт работы в сфере онлайн-обучения'),
        ),
        migrations.AlterField(
            model_name='eios',
            name='q2',
            field=models.CharField(choices=[('0', 'Электронные библиотечные сервисы'), ('1', 'СДО «Гиперметод»'), ('2', 'СДО «Портал электронного обучения на базе Moodle»'), ('3', 'Платформа онлайн-обучения «openedu.urfu.ru»'), ('4', 'Личный кабинет преподавателя'), ('5', 'Ни одним из этих')], max_length=10, verbose_name='Какими корпоративными сервисами Уральского федерального университета вы пользуетесь?'),
        ),
        migrations.AlterField(
            model_name='eios',
            name='q3',
            field=models.CharField(choices=[('0', 'Абсолютно не согласен'), ('1', 'Частично не согласен'), ('2', 'Затрудняюсь ответить'), ('3', 'Частично согласен'), ('4', 'Абсолютно согласен')], default='2', max_length=1, verbose_name='Мне понятен термин “электронная информационно-образовательная среда”'),
        ),
        migrations.AlterField(
            model_name='eios',
            name='q4',
            field=models.CharField(choices=[('0', 'Абсолютно не согласен'), ('1', 'Частично не согласен'), ('2', 'Затрудняюсь ответить'), ('3', 'Частично согласен'), ('4', 'Абсолютно согласен')], default='2', max_length=1, verbose_name='Я понимаю, зачем нужно внедрять онлайн-обучение в образовательную деятельность'),
        ),
        migrations.AlterField(
            model_name='eios',
            name='q5',
            field=models.CharField(choices=[('0', 'Абсолютно не согласен'), ('1', 'Частично не согласен'), ('2', 'Затрудняюсь ответить'), ('3', 'Частично согласен'), ('4', 'Абсолютно согласен')], default='2', max_length=1, verbose_name='Я знаю, с помощью каких инструментов осуществляется онлайн-обучение'),
        ),
        migrations.AlterField(
            model_name='eios',
            name='q6',
            field=models.CharField(choices=[('0', 'Абсолютно не согласен'), ('1', 'Частично не согласен'), ('2', 'Затрудняюсь ответить'), ('3', 'Частично согласен'), ('4', 'Абсолютно согласен')], default='2', max_length=1, verbose_name='Меня интересует онлайн-обучение'),
        ),
        migrations.AlterField(
            model_name='eios',
            name='q7',
            field=models.CharField(choices=[('0', 'Абсолютно не согласен'), ('1', 'Частично не согласен'), ('2', 'Затрудняюсь ответить'), ('3', 'Частично согласен'), ('4', 'Абсолютно согласен')], default='2', max_length=1, verbose_name='Я понимаю финансовые аспекты использования открытых онлайн-курсов'),
        ),
        migrations.AlterField(
            model_name='eios',
            name='q8',
            field=models.CharField(choices=[('0', 'Абсолютно не согласен'), ('1', 'Частично не согласен'), ('2', 'Затрудняюсь ответить'), ('3', 'Частично согласен'), ('4', 'Абсолютно согласен')], default='2', max_length=1, verbose_name='Я понимаю, кто такой тьютор в онлайн-обучении'),
        ),
        migrations.AlterField(
            model_name='eios',
            name='q9',
            field=models.CharField(choices=[('0', 'Абсолютно не согласен'), ('1', 'Частично не согласен'), ('2', 'Затрудняюсь ответить'), ('3', 'Частично согласен'), ('4', 'Абсолютно согласен')], default='2', max_length=1, verbose_name='Мне понятны особенности планирования и реализации учебного процесса для разных моделей включения онлайн-курсов в образовательные программы'),
        ),
    ]
