# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-07 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0005_auto_20180507_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eios',
            name='q2',
            field=models.CharField(choices=[('0', 'Электронные библиотечные сервисы'), ('1', 'СДО «Гиперметод»'), ('2', 'СДО «Портал электронного обучения на базе Moodle»'), ('3', 'Платформа онлайн-обучения «openedu.urfu.ru»'), ('4', 'Личный кабинет преподавателя'), ('5', 'Ни одним из этих')], default='5', max_length=10, verbose_name='Какими корпоративными сервисами Уральского федерального университета вы пользуетесь?'),
        ),
    ]
