# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-07 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0006_auto_20180507_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eios',
            name='q2',
            field=models.CharField(max_length=1024, verbose_name='Какими корпоративными сервисами Уральского федерального университета вы пользуетесь?'),
        ),
    ]
