# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-07 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0007_auto_20180507_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eios',
            name='q11',
            field=models.CharField(choices=[('m', 'Мужской'), ('f', 'Женский')], default='m', max_length=1, verbose_name='Укажите Ваш пол:'),
        ),
        migrations.AlterField(
            model_name='eios',
            name='q12',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Ваш возраст:'),
        ),
    ]
