# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-07 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0008_auto_20180507_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eios',
            name='q13',
            field=models.CharField(choices=[('0', '1-5'), ('1', '6-10'), ('2', '11-15'), ('3', '16-20'), ('4', 'Больше 21')], default='0', max_length=10, verbose_name='Каков Ваш опыт работы в качестве преподавателя?'),
        ),
    ]
