# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-07 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0009_auto_20180507_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eios',
            name='q13',
            field=models.CharField(choices=[('0', '1-5 лет'), ('1', '6-10 лет'), ('2', '11-15 лет'), ('3', '16-20 лет'), ('4', 'Больше 21 года')], default='0', max_length=10, verbose_name='Каков Ваш опыт работы в качестве преподавателя?'),
        ),
        migrations.AlterField(
            model_name='eios',
            name='q14',
            field=models.CharField(choices=[('0', 'Нет'), ('1', 'Кандидат наук'), ('2', 'Доктор наук')], default='0', max_length=1, verbose_name='Наличие ученой степени:'),
        ),
        migrations.AlterField(
            model_name='eios',
            name='q15',
            field=models.EmailField(max_length=254, verbose_name='Контактная почта:'),
        ),
        migrations.AlterField(
            model_name='eios',
            name='q16',
            field=models.CharField(choices=[('y', 'Да'), ('n', 'Нет')], default='y', max_length=1, verbose_name='Интересно ли Вам дальнейшее информирование про мероприятия, связанные с онлайн-обучением)'),
        ),
    ]
