# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-07 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0010_auto_20180507_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eios',
            name='q14',
            field=models.CharField(choices=[('0', 'Нет'), ('1', 'Кандидат наук'), ('2', 'Доктор наук')], default='0', max_length=10, verbose_name='Наличие ученой степени:'),
        ),
    ]
