# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-31 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0011_auto_20180507_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eios',
            name='q11',
            field=models.CharField(choices=[('m', 'Мужской'), ('f', 'Женский')], default='m', max_length=1, verbose_name='Укажите ваш пол:'),
        ),
        migrations.AlterField(
            model_name='eios',
            name='q13',
            field=models.CharField(choices=[('0', '1-5 лет'), ('1', '6-10 лет'), ('2', '11-15 лет'), ('3', '16-20 лет'), ('4', 'Больше 21 года')], default='0', max_length=10, verbose_name='Каков ваш опыт работы в качестве преподавателя?'),
        ),
        migrations.AlterField(
            model_name='eios',
            name='q16',
            field=models.CharField(choices=[('y', 'Да'), ('n', 'Нет')], default='y', max_length=1, verbose_name='Интересно ли вам дальнейшее информирование про мероприятия, связанные с онлайн-обучением?'),
        ),
    ]
