# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 09:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, verbose_name='FIO')),
                ('regalia', models.CharField(max_length=1024, verbose_name='Regalia')),
                ('achievements', models.CharField(blank=True, max_length=1024, verbose_name='Achievements')),
                ('description', models.CharField(blank=True, max_length=1024, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='../uploads/authors/', verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, verbose_name='FIO')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=16, verbose_name='Phone number')),
                ('done', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Minor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, null=True, verbose_name='Minor name')),
                ('description', models.TextField(blank=True, default='Minor description', max_length=256, verbose_name='Description')),
                ('author', models.CharField(max_length=64, null=True, verbose_name='Author')),
                ('institute', models.CharField(max_length=64, null=True, verbose_name='Institute')),
                ('laboriousness', models.FloatField(default=0, verbose_name='Laboriousness')),
                ('weight', models.CharField(max_length=64, null=True, verbose_name='Weight')),
                ('annotation', models.TextField(max_length=32768, null=True, verbose_name='Annotation')),
                ('author_about', models.TextField(max_length=4096, null=True, verbose_name='Author about')),
                ('startdate', models.DateTimeField(null=True, verbose_name='Start date')),
                ('enddate', models.DateTimeField(null=True, verbose_name='End date')),
                ('image', models.ImageField(null=True, upload_to='../uploads/minors/', verbose_name='Image')),
                ('schedule', models.CharField(blank=True, max_length=64, verbose_name='Schedule')),
                ('publiched', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('authors', models.ManyToManyField(blank=True, to='minors.Author')),
            ],
        ),
        migrations.CreateModel(
            name='OOPBid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=2048, null=True, verbose_name='Name')),
                ('email', models.CharField(blank=True, max_length=2048, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=2048, null=True, verbose_name='Phone')),
                ('program', models.CharField(blank=True, max_length=2048, null=True, verbose_name='Program')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Message')),
                ('done', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='bid',
            name='minor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='minors.Minor'),
        ),
    ]
