# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'автор', 'verbose_name_plural': 'авторы'},
        ),
        migrations.AlterModelOptions(
            name='bid',
            options={'verbose_name': 'заявка на майнор', 'verbose_name_plural': 'заявки на майнор'},
        ),
        migrations.AlterModelOptions(
            name='minor',
            options={'verbose_name': 'майнор', 'verbose_name_plural': 'майноры'},
        ),
        migrations.AlterModelOptions(
            name='oopbid',
            options={'verbose_name': 'заявка на открытую программу', 'verbose_name_plural': 'заявки на открытую программу'},
        ),
        migrations.RenameField(
            model_name='minor',
            old_name='publiched',
            new_name='published',
        ),
        migrations.AlterField(
            model_name='minor',
            name='annotation',
            field=models.TextField(max_length=32768, null=True, verbose_name='Аннотация'),
        ),
        migrations.AlterField(
            model_name='minor',
            name='author',
            field=models.CharField(max_length=64, null=True, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='minor',
            name='author_about',
            field=models.TextField(max_length=4096, null=True, verbose_name='Об авторе'),
        ),
        migrations.AlterField(
            model_name='minor',
            name='description',
            field=models.TextField(blank=True, default='Minor description', max_length=256, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='minor',
            name='enddate',
            field=models.DateTimeField(null=True, verbose_name='Дата завершения'),
        ),
        migrations.AlterField(
            model_name='minor',
            name='image',
            field=models.ImageField(null=True, upload_to='../uploads/minors/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='minor',
            name='institute',
            field=models.CharField(max_length=64, null=True, verbose_name='Институт'),
        ),
        migrations.AlterField(
            model_name='minor',
            name='laboriousness',
            field=models.FloatField(default=0, verbose_name='Трудоёмкость'),
        ),
        migrations.AlterField(
            model_name='minor',
            name='name',
            field=models.CharField(max_length=1024, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='minor',
            name='schedule',
            field=models.CharField(blank=True, max_length=64, verbose_name='Расписание'),
        ),
        migrations.AlterField(
            model_name='minor',
            name='startdate',
            field=models.DateTimeField(null=True, verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='minor',
            name='weight',
            field=models.CharField(max_length=64, null=True, verbose_name='Стоимость'),
        ),
    ]
