# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minors', '0003_auto_20170710_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='achievements',
            field=models.CharField(blank=True, max_length=1024, verbose_name='Достижения'),
        ),
        migrations.AlterField(
            model_name='author',
            name='description',
            field=models.CharField(blank=True, max_length=1024, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='author',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='../uploads/authors/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=1024, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='author',
            name='regalia',
            field=models.CharField(max_length=1024, verbose_name='Регалии'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='name',
            field=models.CharField(max_length=1024, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='oopbid',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='oopbid',
            name='name',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='oopbid',
            name='phone',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='oopbid',
            name='program',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='Программа'),
        ),
    ]
