# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 23:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minors', '0004_auto_20170715_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='authors/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='minor',
            name='image',
            field=models.ImageField(null=True, upload_to='minors/', verbose_name='Изображение'),
        ),
    ]
