# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minors', '0005_auto_20170905_0430'),
    ]

    operations = [
        migrations.AddField(
            model_name='oopbid',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='oopbid',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
