# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-12 05:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minors', '0007_quotebid'),
    ]

    operations = [
        migrations.AddField(
            model_name='minor',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Активен'),
        ),
    ]
